name: React front-end deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dannybuilds/react-front-end -f Dockerfile.dev .
      - run: docker run -e CI=true dannybuilds/react-front-end npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
